version: '3.9'
services:
  template:
    build:
      context: .
    ports:
      - 5001:80
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    hostname: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres: